name: Alive
on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"

jobs:
  cronjob-based-github-action:
    name: Dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
